"""empty message

Revision ID: 22f91064f86a
Revises: 250e73b839db
Create Date: 2022-08-04 16:28:57.365303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f91064f86a'
down_revision = '250e73b839db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiments', sa.Column('sentiment_text', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'sentiments', ['sentiment_text'])
    op.drop_column('sentiments', 'sentiment_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiments', sa.Column('sentiment_title', sa.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'sentiments', type_='unique')
    op.drop_column('sentiments', 'sentiment_text')
    # ### end Alembic commands ###
