"""empty message

Revision ID: 250e73b839db
Revises: 8eff35f4e7ae
Create Date: 2022-08-04 16:01:17.386175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250e73b839db'
down_revision = '8eff35f4e7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trust_factors',
    sa.Column('factor_id', sa.Integer(), nullable=False),
    sa.Column('factor_name', sa.String(length=100), nullable=False),
    sa.Column('factor_slug', sa.String(length=100), nullable=False),
    sa.Column('factor_desc', sa.Text(), nullable=True),
    sa.Column('factor_products', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('factor_id'),
    sa.UniqueConstraint('factor_name'),
    sa.UniqueConstraint('factor_slug')
    )
    op.create_table('sentiments',
    sa.Column('sentiment_id', sa.Integer(), nullable=False),
    sa.Column('sentiment_title', sa.String(length=100), nullable=False),
    sa.Column('sentiment_factor', sa.Integer(), nullable=False),
    sa.Column('sentiment_product', sa.Integer(), nullable=False),
    sa.Column('sentiment_platform', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sentiment_factor'], ['trust_factors.factor_id'], ),
    sa.ForeignKeyConstraint(['sentiment_platform'], ['ecommerce_platforms.platform_id'], ),
    sa.ForeignKeyConstraint(['sentiment_product'], ['ecommerce_products.product_id'], ),
    sa.PrimaryKeyConstraint('sentiment_id'),
    sa.UniqueConstraint('sentiment_title')
    )
    op.drop_table('trust_facors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trust_facors',
    sa.Column('factor_id', sa.INTEGER(), nullable=False),
    sa.Column('factor_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('factor_slug', sa.VARCHAR(length=100), nullable=False),
    sa.Column('factor_desc', sa.TEXT(), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=False),
    sa.Column('factor_products', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('factor_id'),
    sa.UniqueConstraint('factor_name'),
    sa.UniqueConstraint('factor_slug')
    )
    op.drop_table('sentiments')
    op.drop_table('trust_factors')
    # ### end Alembic commands ###
