"""empty message

Revision ID: 8eff35f4e7ae
Revises: 26276ed5484e
Create Date: 2022-08-03 22:43:51.011763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eff35f4e7ae'
down_revision = '26276ed5484e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trust_facors', sa.Column('factor_products', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trust_facors', 'factor_products')
    # ### end Alembic commands ###
