"""empty message

Revision ID: c8854d0ad249
Revises: d3e349d3a7ee
Create Date: 2022-07-09 01:53:05.222601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8854d0ad249'
down_revision = 'd3e349d3a7ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('E_commerce_platforms',
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=100), nullable=False),
    sa.Column('platform_slug', sa.String(length=100), nullable=False),
    sa.Column('platform_desc', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('platform_id'),
    sa.UniqueConstraint('platform_name'),
    sa.UniqueConstraint('platform_slug')
    )
    op.create_table('E_commerce_products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('product_slug', sa.String(length=100), nullable=False),
    sa.Column('product_desc', sa.Text(), nullable=True),
    sa.Column('product_platform', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_name'),
    sa.UniqueConstraint('product_slug')
    )
    op.create_table('trust_facors',
    sa.Column('factor_id', sa.Integer(), nullable=False),
    sa.Column('factor_name', sa.String(length=100), nullable=False),
    sa.Column('factor_slug', sa.String(length=100), nullable=False),
    sa.Column('factor_desc', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('factor_id'),
    sa.UniqueConstraint('factor_name'),
    sa.UniqueConstraint('factor_slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trust_facors')
    op.drop_table('E_commerce_products')
    op.drop_table('E_commerce_platforms')
    # ### end Alembic commands ###
