"""empty message

Revision ID: f6e881c5e6f3
Revises: 22f91064f86a
Create Date: 2022-08-04 16:35:10.595031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e881c5e6f3'
down_revision = '22f91064f86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiments',
    sa.Column('sentiment_id', sa.Integer(), nullable=False),
    sa.Column('sentiment_text', sa.String(length=100), nullable=False),
    sa.Column('sentiment_factor', sa.Integer(), nullable=False),
    sa.Column('sentiment_product', sa.Integer(), nullable=False),
    sa.Column('sentiment_platform', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sentiment_factor'], ['trust_factors.factor_id'], ),
    sa.ForeignKeyConstraint(['sentiment_platform'], ['ecommerce_platforms.platform_id'], ),
    sa.ForeignKeyConstraint(['sentiment_product'], ['ecommerce_products.product_id'], ),
    sa.PrimaryKeyConstraint('sentiment_id'),
    sa.UniqueConstraint('sentiment_text')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentiments')
    # ### end Alembic commands ###
